server:
  port: 8080
spring:
  application:
    name: athlete-performance-api
  datasource:
    url: jdbc:postgresql://postgres:5432/athlete_performance_db
    username: athlete_user
    password: dev_password_2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Changed from create-drop to validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
logging:
  level:
    com.athleteperformance: DEBUG
    org.springframework.jdbc: DEBUG
    org.flywaydb: DEBUG  # Added for Flyway logging